### health
GET https://localhost:2121/pulse

###
POST https://localhost:2121/register
Content-Type: application/json

{
  "echo_trees": [],
  "username": "user1",
  "password": "password1"
}

###
DELETE https://localhost:2121/register/f899e5dd-0804-4e43-8733-7f6f289228ce